class MaterialData {

  final String? title; //"Сасаки и Мияно",
  final String? animeTitle; //"Сасаки и Мияно",
  final String? titleEn; //"Sasaki to Miyano",
  final List<String>? otherTitles; //["Sasamiya"],
  final List<String>? otherTitlesEn; //["Sasaki and Miyano"],
  final List<String>? otherTitlesJp; //["佐々木と宮野"],
  final String? animeLicenseName; //"Сасаки и Мияно",
  final String? animeLicensedBy; //["Wakanim"],
  final String? animeKind; //"tv",
  final String? allStatus; //"ongoing",
  final String? animeStatus; //"ongoing",
  final String? description; //"Ничто не нарушало мирных будней Ёсикадзу Мияно: он учился,
  final String? animeDescription; //"Ничто не нарушало мирных будней Ёсикадзу Мияно: он учился,
  final String? posterUrl; //"https://st.kp.yandex.net/images/film_big/4557186.jpg",
  final List<String>? screenshots; //["https://shikimori.one/system/screenshots/original/158979ea6daf47fad1e8219942e6d21495ad5079.jpg",
  final String? https; //shikimori.one/system/screenshots/original/0d6161df014369b2f8e23a8b0dba4709c87a8023.jpg"],
  final double? duration; //23,
  final String? countries; //["Япония"],
  final List<String>? allGenres;
  final List<String>? genres;
  final List<String>? animeGenres;
  final List<String>? animeStudios;
  final double? imdbRating; //7.6,
  final int? imdbVotes; //136,
  final double? shikimoriRating; //7.93,
  final int? shikimoriVotes; //342,
  final String? premiereWorld; //"2022-01-10",
  final String? airedAt; //"2022-01-10",
  final String? releasedAt; //"2022-03-28",
  final String? nextEpisodeAt; //"2022-02-20T15:30:00Z",
  final String? ratingMpaa; //"PG-13",
  final int? minimalAge; //18,
  final int? episodesTotal; //12,
  final int? episodesAired; //6,
  final List<String>? actors;
  final List<String>? directors;
  final List<String>? writers;

  MaterialData(
      this.title,
      this.animeTitle,
      this.titleEn,
      this.otherTitles,
      this.otherTitlesEn,
      this.otherTitlesJp,
      this.animeLicenseName,
      this.animeLicensedBy,
      this.animeKind,
      this.allStatus,
      this.animeStatus,
      this.description,
      this.animeDescription,
      this.posterUrl,
      this.screenshots,
      this.https,
      this.duration,
      this.countries,
      this.allGenres,
      this.genres,
      this.animeGenres,
      this.animeStudios,
      this.imdbRating,
      this.imdbVotes,
      this.shikimoriRating,
      this.shikimoriVotes,
      this.premiereWorld,
      this.airedAt,
      this.releasedAt,
      this.nextEpisodeAt,
      this.ratingMpaa,
      this.minimalAge,
      this.episodesTotal,
      this.episodesAired,
      this.actors,
      this.directors,
      this.writers);
}